/* Generated by NinjaPilot's version-info.py at configure time. */
#pragma once
#include <stdint.h>

#define FW_VERSION_HASH32   0x${HASH8}u
#define FW_VERSION_UNIXTIME ${UNIXTIME}u
#define FW_VERSION_FWTAG    "${FWTAG}"
static const uint8_t fw_version_uavo_sha1[20] = { ${UAVO_HASH_ARRAY} };
